# Generated by Django 2.2.10 on 2021-07-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210719_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='Pic',
            field=models.ImageField(null=True, upload_to='con'),
        ),
    ]
