# Generated by Django 2.2.10 on 2021-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_contestant_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='Status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
