# Generated by Django 2.2.10 on 2021-07-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_election_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='Pic',
            field=models.ImageField(null=True, upload_to='icon'),
        ),
    ]
