# Generated by Django 2.2.10 on 2021-07-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210719_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Contestant')),
                ('Voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Voter')),
            ],
        ),
    ]
