# Generated by Django 2.2.10 on 2021-07-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Election'),
        ),
    ]
