# Generated by Django 2.2.10 on 2021-07-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_vote_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='End',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='Start',
            field=models.DateTimeField(null=True),
        ),
    ]
