# Generated by Django 2.2.10 on 2021-07-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210719_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='Leader',
            field=models.BooleanField(default=False),
        ),
    ]
