# Generated by Django 2.2.10 on 2021-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_voter_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='Cohort',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
