# Generated by Django 2.2.10 on 2021-07-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20210721_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initials', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=60)),
            ],
        ),
    ]
