# Generated by Django 2.2.10 on 2021-07-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='Department',
        ),
    ]
