# Generated by Django 2.2.10 on 2021-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_remove_voter_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('File', models.FileField(max_length=1000, upload_to='files')),
            ],
        ),
    ]
