# Generated by Django 2.2.10 on 2021-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_studentcvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='Eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='Explanation',
            field=models.TextField(null=True),
        ),
    ]
