# Generated by Django 2.2.10 on 2021-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20210722_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='Activated',
            field=models.BooleanField(default=False),
        ),
    ]
