# Generated by Django 2.2.10 on 2021-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_vote_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=50)),
            ],
        ),
    ]
